var blockColors = {
    "purple":"#EE00EE",
    "blue":"#1122EE",
    "yellow":"#FFFF00",
    "red":"#FF0000",
    "orange":"#FF6600",
    "green":"#00FF00",
    "break":"#FFF"
}
var blocks = {
    "Mon": [
        {
        "start":"09:00",
        "end":"10:30",
        "color":blockColors.break,
        "name":"Homebase"
        },
        {
        "start":"10:30",
        "end":"12:45",
        "color":blockColors.break,
        "name":"Break"
        },
        {
        "start":"10:45",
        "end":"12:15",
        "color":blockColors.green,
        "name":"Green"
        },
        {
        "start":"12:15",
        "end":"13:00",
        "color":blockColors.break,
        "name":"Lunch"
        },
        {
        "start":"13:00",
        "end":"14:30",
        "color":blockColors.red,
        "name":"Red"
        }
    ],
    "Tue": [
        {
        "start":"09:00",
        "end":"10:30",
        "color":blockColors.purple,
        "name":"Purple"
        },
        {
        "start":"10:30",
        "end":"12:45",
        "color":blockColors.break,
        "name":"Break"
        },
        {
        "start":"10:45",
        "end":"12:15",
        "color":blockColors.blue,
        "name":"Blue"
        },
        {
        "start":"12:15",
        "end":"13:00",
        "color":blockColors.break,
        "name":"Lunch"
        },
        {
        "start":"13:00",
        "end":"14:30",
        "color":blockColors.orange,
        "name":"Orange"
        }
    ],
    "Wed": [
        {
        "start":"09:00",
        "end":"10:30",
        "color":blockColors.break,
        "name":"Homebase"
        },
        {
        "start":"10:30",
        "end":"12:45",
        "color":blockColors.break,
        "name":"Break"
        },
        {
        "start":"10:45",
        "end":"12:15",
        "color":blockColors.red,
        "name":"Red"
        },
        {
        "start":"12:15",
        "end":"13:00",
        "color":blockColors.break,
        "name":"Lunch"
        },
        {
        "start":"13:00",
        "end":"14:30",
        "color":blockColors.yellow,
        "name":"Yellow"
        }
    ],
    "Thu": [
        {
        "start":"09:00",
        "end":"10:30",
        "color":blockColors.break,
        "name":"Purple"
        },
        {
        "start":"10:30",
        "end":"12:45",
        "color":blockColors.break,
        "name":"Break"
        },
        {
        "start":"10:45",
        "end":"12:15",
        "color":blockColors.orange,
        "name":"Orange"
        },
        {
        "start":"12:15",
        "end":"13:00",
        "color":blockColors.break,
        "name":"Lunch"
        },
        {
        "start":"13:00",
        "end":"14:30",
        "color":blockColors.green,
        "name":"Green"
        }
    ],
    "Fri": [
        {
        "start":"09:00",
        "end":"10:30",
        "color":blockColors.break,
        "name":"Homebase"
        },
        {
        "start":"10:30",
        "end":"12:45",
        "color":blockColors.break,
        "name":"Break"
        },
        {
        "start":"10:45",
        "end":"12:15",
        "color":blockColors.yellow,
        "name":"Yellow"
        },
        {
        "start":"12:15",
        "end":"13:00",
        "color":blockColors.break,
        "name":"Lunch"
        },
        {
        "start":"13:00",
        "end":"14:30",
        "color":blockColors.blue,
        "name":"Blue"
        }
    ]
}